apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookservice
  template:
    metadata:
      labels:
        app: bookservice
    spec:
      containers:
        - name: bookservice
          image: library-microservices-bookservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
